import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { TopBanner } from "../stories/TopBanner/TopBanner";
import React from "react";
import { BorderNav } from "../stories/Navigation/BorderNavigation/BorderNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NavLinks = [
  { name: "home", label: "home", href: "/" },
  { name: "work with me", label: "services", href: "/services" },
  { name: "portfolio", label: "portfolio", href: "/portfolio" },
  { name: "book your project", label: "connect", href: "/connect" },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBanner
          label={"NOW BOOKING PROJECTS FOR Q1 OF 2024"}
          theme="primary"
          link="/connect"
        />
        <BorderNav links={NavLinks} />
        {children}
      </body>
    </html>
  );
}
